version: '2'
services:
  web:
    container_name: "agario-${SERVER_PORT}"
    hostname: "agario-${SERVER_PORT}"
    build: .
    ports:
      - "${SERVER_PORT}:3000"
    volumes:
      - ./config/config.json:/usr/app/config.json
